### ISSUE TITLE
@Option to enable export feature for PitestTask

### ISSUE THREAD

**Issue by Vampire** [szpak/gradle-pitest-plugin#139]
Since Gradle 4.6 you can add custom command-line flags for tasks using the `@Option` annotation.
It would be nice if the `PitestTask` had such an option that enables the `EXPORT` feature, so that you can decide on each run easily whether you want the mutants to be dumped on disk or not without having to edit the build script or implementing the logic using a project property in each build individually.

**Comment by szpak** [comment]
I tried to implement it in a natural way - with an ability to override `features` property, but I ran into Gradle limitations. Mostly https://github.com/gradle/gradle/issues/10517, but also https://github.com/gradle/gradle/issues/4311 and https://github.com/gradle/gradle/issues/10518.

I don't know if I would like to implement any "hack" to just allow to enable `EXPORT`. In hindsight, I should rethink introduction of Property API (#105) as due to limitations the old mechanism had to stay for part of the values (no real gain for the others), it blocks some features and it took too much time to implement...

Btw, unfortunately, the other plugin for configuration overriding also doesn't support collections: https://github.com/nebula-plugins/gradle-override-plugin/issues/3

**Comment by Vampire** [comment]
Just in case you don't know, Spock has a `@PendingFeature` annotation, that you can use instead of `@Ignore`.
That will report the test as skipped as long as the tests fail and once all iterations of the feature are successful, the feature is deemed implemented and the test begins to fail, so that the `@PendingFeature` annotation can be removed.

> I don't know if I would like to implement any "hack" to just allow to enable EXPORT.

Actually I wouldn't consider this a hack, but exactly what I wanted.
I don't want an option that overrides all features.
I have in my build script disabled `-FLOGCALL` for now, but I could have other features configured.
I really would like to be able to just add to that the `+EXPORT` feature instead of replacing the list of features.

**Comment by szpak** [comment]
Yes, I know `@PendingFeature` and I intended to use it :).

I implemented `--additionalFeatures=+EXPORT`. Please take a look at the new commit and provide feedback based on the latest uploaded 1.4.6-SNAPSHOT.

**Comment by Vampire** [comment]
I didn't test it yet, but from what I see in the commit, it looks nice, thanks :-)
