### ISSUE TITLE
set `targetTests` explicitly

### ISSUE THREAD

**Issue by Vampire** [szpak/gradle-pitest-plugin#144]
According to http://pitest.org/quickstart/commandline/ it is recommended to always set `targetTests` parameter explicitly.
This plugin does only set the `targetClasses` explicitly which then is used for both parameters.
To save some time during targeted work I set `targetClasses` to the classes I'm currently working on and then wondered why there are no tests found anymore.
I'd like to recommend to also set `targetTests` explicitly by default.

**Comment by szpak** [comment]
@Vampire You may want to check 1.4.6-SNAPSHOT if it works for you.

**Comment by Vampire** [comment]
I had a quick look at the commit you made.
Actually besides following the recommendation by PIT to always set it explicitly,
like you did it there will end up in the same result, the `targetClasses` value being used.

I don't think this makes much sense and would have led to the same confusion I had
that I described in the original comment.

Here some alternatives one of which might makes sense to you to adapt instead of what you did right now:
- maybe it would make sense to assume some common naming convention and have as default value something like `[[project.getGroup() + '.*'], ['Test', 'Spec'], ['*']].combinations()*.join()`
- or maybe list as default all classes in the test source set, suffixed with `*` to also catch inner classes
- or if you don't like all of this, at least make `targetTests` independent from `targetClasses`, they can have the same default value, but if I set `targetClasses` to explicit classes it is still very confusing if suddenly no tests are found because they do not match that pattern

**Comment by szpak** [comment]
> or if you don't like all of this, at least make targetTests independent from targetClasses, they can have the same default value, but if I set targetClasses to explicit classes it is still very confusing if suddenly no tests are found because they do not match that pattern
I don't understand that. If you set `targetClasses` to anything it is passed to PIT:
```
    @Issue("https://github.com/szpak/gradle-pitest-plugin/issues/144")
    def "should set targetTest to configuration defined value"() {
        when:
            project.pitest.targetClasses = ["myClasses.*"]
            project.pitest.targetTests = ["myClasses.tests.*"]
        then:
            task.createTaskArgumentMap()['targetTests'] == "myClasses.tests.*"
    }
```
Unless there is (or was) a bug it should work like that also in 1.4.0.

**Comment by szpak** [comment]
Regarding the general case, I'm not convinced that I want to change the default behavior. Very often people don't set anything (`group` is used) or set the main package in `targetClasses` and expect that everything will work. As I'm not able to easily (and reliably) distinguish if a developer set "main package" or "just one small subpackage" following `targetClasses` in `targetTests` would work in most of (generic) cases - it's safe. Otherwise, people setting the main package could end up with no tests (luckily detected by PIT). Focused work on mutation it's usually temporary and it is easier to explicitly set `targetTests` then.
Of course there are some cases where that approach will fail and people would need to set `targetClasses` on them own, but IMO letting it (usually) work by default is more sensible. WDYT?

**Comment by szpak** [comment]
Btw, I implemented an ability to override `targetTests` from command line (#143), so maybe it is not so important to tune for "focused cases"?

**Comment by Vampire** [comment]
Well, given are right regarding the "people set targetClasses and expect that the tests are following suit", the current default might be good.
I was just majorly confused by that behaviour.
If you don't want to change it, fine, I'm aware of it now and especially with #143 will probably not set it in the script anyway. :-)
