### ISSUE TITLE
Regression: Version 1.5.0 fails to load the JUnit5 plugin (worked in 1.4.9)

### ISSUE THREAD

**Issue by christianhujer** [szpak/gradle-pitest-plugin#204]
When changing the PiTest Gradle plugin version from 1.4.9 to 1.5.0, PiTest stops working. The problem is that it can no longer load the JUnit 5 plugin.

Example project: https://github.com/nelkinda/template-java-gradle
Steps to reproduce:
1. Clone https://github.com/nelkinda/template-java-gradle
2. Change build.gradle PiTest Plugin from 1.4.9, and add `verbose = true` to the `pitest{}` section
3. Run `make && make pitest`

Expected behavior: PiTest stops saying that no mutants were generated (there is no production code in the template project)
Actual behavior: PiTest stops saying that it couldn't load the JUnit 5 plugin.

**Comment by szpak** [comment]
Have you performed the steps mentioned in the [release notes](https://github.com/szpak/gradle-pitest-plugin/releases/tag/release%2F1.5.0)?

Next to the section "**Compatibility changes**".

**Comment by christianhujer** [comment]
That worked. I didn't expect a version change from 1.4.9 to 1.5.0 to require looking at the release notes.

**Comment by szpak** [comment]
That's why it was 1.5.0 not 1.4.10 :). Due to semantic versioning in PIT, it is somehow problematic to keep Semantic Versioning.

Btw, with 1.4.7+ you can simplify your JUnit 5 plugin configuration greatly:
https://blog.solidsoft.pl/2020/02/27/pit-junit-5-and-gradle-with-just-one-extra-line-of-configuration/
