### ISSUE TITLE
Remove Gradle 4.0 workaround from PitestTask.exec

### ISSUE THREAD

**Issue by pkubowicz** [szpak/gradle-pitest-plugin#217]
The comment says:
```groovy
//Workaround for compatibility with Gradle <4.0 due to setArgs(List) and setJvmArgs(List) added in Gradle 4.0
```
but the plugin requires Gradle 5.6 at minimum.

**Comment by szpak** [comment]
You are right. I will remove it along the way with the other code modifications.

**Comment by pkubowicz** [comment]
Are you sure this is correct? This commit removed just the comment.

**Comment by szpak** [comment]
I also expected something bigger, but looking at the old [commit](https://github.com/szpak/gradle-pitest-plugin/commit/1103f2a8bd7ac2350c5f48b26e80fe07fbf9dbfe#diff-5e4a3573f379a6ec10d65eecd5323d47L192-R196) I switched from calling the setter directly and probably with settings some protected field directly (due to some compatibility issues with lower Gradle 4.x - based on the comments - it was Sep 5, 2017). However, that Groovy syntax currently seems to call setters under the hood (field could be removed in the meantime), so it is also fine (for Groovy code).
