### ISSUE TITLE
TestNG groups exclusion is not supported

### ISSUE THREAD

**Issue by swarr** [szpak/gradle-pitest-plugin#27]
Observed for pitest plugin 1.1.4; pitest 1.1.5

According to test on http://gradle-pitest-plugin.solidsoft.info/ "All the command line options are supported." but actually adding "includedTestNGGroups" to pitest configuration closure leads to exception "No such property: excludedTestNGGroups for class: info.solidsoft.gradle.pitest.PitestPluginExtension_Decorated". 

Note, that "excludedGroups" is not working for TestNG groups as well.

**Comment by szpak** [comment]
Thanks for your report. `excludedGRoups` property was [renamed](https://github.com/szpak/gradle-pitest-plugin/issues/13) a while ago due to an upstream change. There seems to be a [PR](https://github.com/hcoles/pitest/issues/120) fixing the Pitest documentation.

I propose you to report problem with documentation and your issue with not working `excludedGroups` to the PIT users mailing list (with a snipped from your Gradle and TestNG configuration).

Closing this issue. Feel free to reopen it if you think is it an issue with the Gradle plugin for PIT.
