### ISSUE TITLE
classPathFile support (PIT 1.1.11)

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#50]
PR in PIT: https://github.com/hcoles/pitest/pull/289

**Comment by szpak** [comment]
Added in 1.1.11.

**Comment by FlasH-RUS** [comment]
I was unable to make it work out of the box for  #276 (i.e. running gradle build on windows machine while having a really long dependency list). Since _taskClasspath_ is still automatically constructed from runtime classpaths of testSourceSets the resulting classpath might still be too long for windows machine even if you are using _classPathFile_.
My WA was to set _classPathFile_ AND erase _testSourceSets_ while still adding all corresponding dependencies into class path file + adding required task dependencies:

    task pitestClassPathFile(dependsOn: testClasses) << {
        Set<String> classPaths = new HashSet<String>();
    
        classPaths.add(sourceSets.test.output.classesDir)
        classPaths.add(sourceSets.test.output.resourcesDir)
        sourceSets.test.compileClasspath.getFiles().forEach { filePath ->
            classPaths.add(filePath)
        }
        sourceSets.test.runtimeClasspath.getFiles().forEach { filePath ->
            classPaths.add(filePath)
        }
    
        StringBuilder classPathFileContents = new StringBuilder()
        classPaths.forEach { filePath ->
            classPathFileContents.append(filePath).append('\n')
        }
    
        def classPathFile = new File("${project.buildDir}/pitestClassPathFile")
        classPathFile.write(classPathFileContents.toString())
    }
    
    pitest {
    ...
        testSourceSets = []
        classPathFile = file("${project.buildDir}/pitestClassPathFile")
    }
    
    tasks['pitest'].dependsOn pitestClassPathFile

**Comment by FlasH-RUS** [comment]
Probably the quickest fix would be to just omit _classPath_ command line argument if it's empty and/or if _classPathFile_ is provided.

**Comment by szpak** [comment]
I was thinking about a similar solution. An additional `useClassPathFile` boolean property to make the plugin use an automatically created file filled with a classPath and to clear up `classPath` parameter passed to PIT.

**Comment by szpak** [comment]
The Gradle plugin itself doesn't provide a direct way to specify a `classpath` path - it is based on the project configuration. It was my overlook to expose `classPathFile` directly in the plugin configuration.

Thanks @FlasH-RUS for spotting the issue.
