### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by ValeryIvanov** [szpak/gradle-pitest-plugin#63]
I have set up pitest plugin exactly like it is said in the documentation but get this error when executing pitest task (`gradlew pitest --stacktrace`).

Root project is Spring Boot application (1.3.2.RELEASE) with couple of submodules and JUnit (4.12) tests. Java 8 is used.

Running pitest with `gradlew pitest --info` command I see that generated classpath is rather long but I am not sure what I can do to solve this problem.

**Comment by szpak** [comment]
There is an ability in PIT to use a file to pass classpath rather than a command line (which is important especially if you are a Windows user). Unfortunately it is broken in the current Gradle plugin version. You can see the discussion and a possible workaround [here](https://github.com/szpak/gradle-pitest-plugin/issues/50#issuecomment-276675197).

To get notification when this issue is fixed please subscribe to #56.
